@baseUrl = http://localhost:5500

GET {{baseUrl}}/user?id=1&key=2 HTTP/1.1

###
POST {{baseUrl}}/user HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}

###
PUT {{baseUrl}}/user HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}

###
PATCH {{baseUrl}}/user HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}

###
DELETE {{baseUrl}}/user HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}

###
POST {{baseUrl}}/home HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}