@baseUrl = http://localhost:5500

GET {{baseUrl}}/user?userId=1&bookId=2 HTTP/1.1

###
GET {{baseUrl}}/user/1/book/2 HTTP/1.1

###
POST {{baseUrl}}/user HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}

###
PUT {{baseUrl}}/user HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}

###
PATCH {{baseUrl}}/user HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}

###
DELETE {{baseUrl}}/user HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}

###
POST {{baseUrl}}/user/add HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}

###
POST {{baseUrl}}/user/remove HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}

###
POST {{baseUrl}}/home HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}

###
POST {{baseUrl}}/article/add HTTP/1.1
Content-Type: application/json

{
  "name": "article1",
  "age": 10
}

###
POST {{baseUrl}}/article/remove HTTP/1.1
Content-Type: application/json

{
  "name": "article2",
  "age": 20
}